apiVersion: apps/v1
kind: Deployment
metadata:
  name: anchor-platform-sep-server
  namespace: anchor-platform
  labels:
    app: anchor-platform-sep-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sep
  template:
    metadata:
      labels:
        app: anchor-platform-sep-server
    spec:
      containers:
      - name: sep-server
        image: stellar/anchor-platform:548a810
        args: ["--sep-server"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: anchor-platform-sep-server-config