apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: anchor-platform
spec:
  ingressClassName: nginx
  rules:
  - host: sep.localdev.me
    http:
      paths:
      - path: /
        backend:
          serviceName: sep-server-service
          servicePort: 8080