apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-staging
 namespace: cert-manager
spec:
 acme:
   # Anchor Platform Sep Server URL
   server: {{ .Values.sep_endpoint}}
   # Email address used for ACME registration
   email: reece@stellar.org
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: letsencrypt-dev
   # Enable the HTTP-01 challenge provider
   solvers:
   - http01:
       ingress:
         class:  nginx
