apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: anchor-platform
  labels:
    app: anchor-platform-reference-server-preview-id
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anchor-platform-reference-server-preview-id
  template:
    metadata:
      labels:
        app: anchor-platform-reference-server-preview-id
    spec:
      containers:
      - name: reference-server
        image: stellar/anchor-platform:e0a7d02
        args: ["--anchor-reference-server"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-configmap
          

