apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: anchor-platform
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8081       # port number the service will listen on
    targetPort: 8081 # port number pods listen on
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: anchor-platform
  app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "public"
    cert-manager.io/cluster-issuer: "default"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/browser-xss-filter: "true"
    ingress.kubernetes.io/frame-deny: "true"
    ingress.kubernetes.io/content-type-nosniff: "true"
    ingress.kubernetes.io/hsts-max-age: "31536000"
    ingress.kubernetes.io/hsts-include-subdomains: "true"
spec:
  tls:
  - secretName: star.previews.kube001.services.stellar-ops.com.tls
  rules:
  - host: anchor-ref-preview-id.previews.kube001.services.stellar-ops.com
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-service
          servicePort: 8081
