apiVersion: apps/v1
kind: Deployment
metadata:
  name: anchor-platform-reference-server-preview-id
  namespace: anchor-platform
  labels:
    app: anchor-platform-reference-server-preview-id
  annotations:
    fluxcd.io/automated: "true"
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anchor-platform-reference-server-preview-id
  template:
    metadata:
      labels:
        app: anchor-platform-reference-server-preview-id
    spec:
      containers:
      - name: reference-server
        image: docker-registry.services.stellar-ops.com/dev/anchor-platform:preview-id
        args: ["--anchor-reference-server"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: anchor-platform-reference-server-config-preview-id
          
